-- [Luau Shield Local Offline Protection]
                                                                                                                                                                                                                                                                                                                                                                local d_k0dmve = {27,26}
                                                                                                                                                                                                                                                                                                                                                                local k_0mql73 = 115
                                                                                                                                                                                                                                                                                                                                                                local r_2zkoxv = {}
                                                                                                                                                                                                                                                                                                                                                                for i_aorw1r = 1, #d_k0dmve do
                                                                                                                                                                                                                                                                                                                                                                    local b_pao6yd = bit32.bxor(d_k0dmve[i_aorw1r], k_0mql73)
                                                                                                                                                                                                                                                                                                                                                                        table.insert(r_2zkoxv, string.char(b_pao6yd))
                                                                                                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                                                                                                        local chunk, err = loadstring(table.concat(r_2zkoxv))
                                                                                                                                                                                                                                                                                                                                                                        if chunk then
                                                                                                                                                                                                                                                                                                                                                                            return chunk()
                                                                                                                                                                                                                                                                                                                                                                            else
                                                                                                                                                                                                                                                                                                                                                                                error("Execution error: " .. tostring(err))
                                                                                                                                                                                                                                                                                                                                                                                end